name: test

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: ubuntu
        run: cd ${{ github.action_path }}

  windows:
    runs-on: windows-2025
    steps:
      - name: windows
        run: cd ${{ github.action_path }}
