name: test

on:
  workflow_dispatch:

jobs:

  windows:
    runs-on: windows-2025
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 99
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 66
          gh_token: ${{ secrets.GITHUB_TOKEN }}
